default: &default
  adapter: mysql2
  encoding: utf8
  pool: 20
  database: bevtracker
  username: <%= ENV['BEVTRACKER'].split(':').first %>
  password: <%= ENV['BEVTRACKER'].split(':').last %>
  host: <%= (`hostname` =~ /^karl\-mbp/) ? 'localhost' : 'kpfalzer-nocal-db.cyxfne3k4fg3.us-west-1.rds.amazonaws.com' %>

development:
  <<: *default

production:
  <<: *default
